# Verified, well-known central government schemes with official source links.
# Source of truth: official scheme portals. Do not fabricate eligibility or deadlines.
# "hi" holds Hindi translations; images are illustrative stock photos.
def _img(pid):
    return f"https://images.unsplash.com/photo-{pid}?w=800&q=70&fm=jpg&fit=crop"


SCHEMES = [
    {
        "id": "pm-kisan",
        "name": "PM-KISAN (Pradhan Mantri Kisan Samman Nidhi)",
        "category": "income_support",
        "level": "central",
        "image": _img("1500937386664-56d1dfef3854"),
        "summary": "Income support of Rs. 6,000 per year to eligible landholding farmer families, paid in three equal installments.",
        "benefits": "Rs. 6,000/year direct benefit transfer in 3 installments of Rs. 2,000.",
        "eligibility": "Landholding farmer families, subject to exclusion criteria (e.g., income tax payers, institutional landholders).",
        "documents": ["Aadhaar", "Land records", "Bank account details"],
        "how_to_apply": "Register on the PM-KISAN portal, through CSC centres, or via state nodal officers. eKYC is mandatory.",
        "official_link": "https://pmkisan.gov.in/",
        "hi": {
            "summary": "पात्र भूमिधारक किसान परिवारों को प्रति वर्ष ₹6,000 की आय सहायता, तीन बराबर किस्तों में।",
            "benefits": "₹2,000 की 3 किस्तों में ₹6,000/वर्ष सीधे बैंक खाते में।",
            "eligibility": "भूमिधारक किसान परिवार (आयकर दाता आदि अपवर्जन नियम लागू)।",
            "how_to_apply": "PM-KISAN पोर्टल, CSC केंद्र या राज्य नोडल अधिकारी के माध्यम से पंजीकरण करें। eKYC अनिवार्य है।",
        },
    },
    {
        "id": "pmfby",
        "name": "PMFBY (Pradhan Mantri Fasal Bima Yojana)",
        "category": "insurance",
        "level": "central",
        "image": _img("1464226184884-fa280b87c399"),
        "summary": "Crop insurance against natural calamities, pests and diseases with low farmer premium rates.",
        "benefits": "Insurance cover for notified crops; farmer premium capped at 2% (Kharif), 1.5% (Rabi), 5% (commercial/horticulture).",
        "eligibility": "All farmers growing notified crops in notified areas, including sharecroppers and tenant farmers.",
        "documents": ["Aadhaar", "Bank account", "Land records / sowing certificate"],
        "how_to_apply": "Through banks, CSCs, insurance intermediaries or the National Crop Insurance Portal. Enrollment windows depend on crop season.",
        "official_link": "https://pmfby.gov.in/",
        "hi": {
            "summary": "प्राकृतिक आपदा, कीट और रोगों से फसल का बीमा — किसान के लिए बहुत कम प्रीमियम पर।",
            "benefits": "अधिसूचित फसलों का बीमा; किसान प्रीमियम खरीफ 2%, रबी 1.5%, वाणिज्यिक/बागवानी 5% तक सीमित।",
            "eligibility": "अधिसूचित क्षेत्रों में अधिसूचित फसल उगाने वाले सभी किसान, बटाईदार और किरायेदार किसान भी।",
            "how_to_apply": "बैंक, CSC, बीमा मध्यस्थ या राष्ट्रीय फसल बीमा पोर्टल से। नामांकन की अवधि फसल सीजन पर निर्भर करती है।",
        },
    },
    {
        "id": "kcc",
        "name": "Kisan Credit Card (KCC)",
        "category": "credit",
        "level": "central",
        "image": _img("1560493676-04071c5f467b"),
        "summary": "Short-term credit for cultivation, post-harvest expenses, and allied activities at concessional interest rates.",
        "benefits": "Credit up to Rs. 3 lakh with interest subvention; covers crop production and allied activities like dairy and fisheries.",
        "eligibility": "Farmers (owner cultivators, tenants, sharecroppers, SHGs/JLGs of farmers).",
        "documents": ["Identity proof", "Address proof", "Land documents"],
        "how_to_apply": "Apply at any bank branch or online through participating bank portals.",
        "official_link": "https://www.myscheme.gov.in/schemes/kcc",
        "hi": {
            "summary": "खेती, कटाई के बाद के खर्च और डेयरी-मत्स्य जैसे कार्यों के लिए रियायती ब्याज पर अल्पकालिक ऋण।",
            "benefits": "ब्याज सहायता के साथ ₹3 लाख तक का ऋण; फसल उत्पादन और संबद्ध गतिविधियां शामिल।",
            "eligibility": "किसान (स्वयं की भूमि वाले, किरायेदार, बटाईदार, किसानों के SHG/JLG)।",
            "how_to_apply": "किसी भी बैंक शाखा में या बैंक पोर्टल से ऑनलाइन आवेदन करें।",
        },
    },
    {
        "id": "soil-health-card",
        "name": "Soil Health Card Scheme",
        "category": "advisory",
        "level": "central",
        "image": _img("1574943320219-553eb213f72d"),
        "summary": "Free soil testing and crop-wise nutrient recommendations to improve soil health and reduce input cost.",
        "benefits": "Soil health card with fertilizer recommendations for your specific field.",
        "eligibility": "All farmers.",
        "documents": ["Basic farmer details", "Field location"],
        "how_to_apply": "Contact local agriculture department or soil testing lab; samples are collected and cards issued.",
        "official_link": "https://soilhealth.dac.gov.in/",
        "hi": {
            "summary": "मुफ्त मिट्टी जांच और फसल-वार पोषक तत्व सिफारिशें — मिट्टी की सेहत सुधारें, लागत घटाएं।",
            "benefits": "आपके खेत के लिए उर्वरक सिफारिशों वाला मृदा स्वास्थ्य कार्ड।",
            "eligibility": "सभी किसान।",
            "how_to_apply": "स्थानीय कृषि विभाग या मिट्टी जांच प्रयोगशाला से संपर्क करें; नमूने लेकर कार्ड जारी किया जाता है।",
        },
    },
    {
        "id": "pm-kusum",
        "name": "PM-KUSUM (Solar Pumps & Renewable Energy)",
        "category": "infrastructure",
        "level": "central",
        "image": _img("1595113316349-9fa4eb24f884"),
        "summary": "Subsidies for standalone solar pumps, solarization of existing pumps, and small solar plants on farm land.",
        "benefits": "Central and state subsidy on solar pump cost (share varies by state and component).",
        "eligibility": "Individual farmers, groups, FPOs, Panchayats depending on component.",
        "documents": ["Identity proof", "Land documents", "Bank details"],
        "how_to_apply": "Through state nodal agencies (state renewable energy departments/DISCOMs).",
        "official_link": "https://pmkusum.mnre.gov.in/",
        "hi": {
            "summary": "सोलर पंप, मौजूदा पंपों के सोलराइजेशन और खेत पर छोटे सोलर प्लांट के लिए सब्सिडी।",
            "benefits": "सोलर पंप की लागत पर केंद्र और राज्य की सब्सिडी (राज्य व घटक के अनुसार)।",
            "eligibility": "व्यक्तिगत किसान, समूह, FPO, पंचायत (घटक के अनुसार)।",
            "how_to_apply": "राज्य नोडल एजेंसियों (नवीकरणीय ऊर्जा विभाग/DISCOM) के माध्यम से।",
        },
    },
    {
        "id": "enam",
        "name": "e-NAM (National Agriculture Market)",
        "category": "market",
        "level": "central",
        "image": _img("1523348837708-15d4a09cfac2"),
        "summary": "Online trading platform connecting APMC mandis, enabling transparent price discovery and online payment.",
        "benefits": "Access to buyers across mandis, transparent auctions, online payments.",
        "eligibility": "Farmers, traders and buyers registered with an e-NAM mandi.",
        "documents": ["Identity proof", "Bank account"],
        "how_to_apply": "Register on the e-NAM portal or at your nearest e-NAM enabled mandi.",
        "official_link": "https://www.enam.gov.in/",
        "hi": {
            "summary": "APMC मंडियों को जोड़ने वाला ऑनलाइन व्यापार मंच — पारदर्शी नीलामी और ऑनलाइन भुगतान।",
            "benefits": "कई मंडियों के खरीदारों तक पहुंच, पारदर्शी बोली, ऑनलाइन भुगतान।",
            "eligibility": "e-NAM मंडी में पंजीकृत किसान, व्यापारी और खरीदार।",
            "how_to_apply": "e-NAM पोर्टल पर या नज़दीकी e-NAM मंडी में पंजीकरण करें।",
        },
    },
    {
        "id": "aif",
        "name": "Agriculture Infrastructure Fund (AIF)",
        "category": "infrastructure",
        "level": "central",
        "image": _img("1416879595882-3373a0480b5b"),
        "summary": "Medium-long term financing for post-harvest infrastructure like warehouses, cold storage, and processing units.",
        "benefits": "3% interest subvention on loans up to Rs. 2 crore and credit guarantee support.",
        "eligibility": "Farmers, FPOs, PACS, SHGs, agri-entrepreneurs, startups.",
        "documents": ["Project report", "KYC", "Land/lease documents"],
        "how_to_apply": "Apply on the AIF portal; sanctioned through lending institutions.",
        "official_link": "https://agriinfra.dac.gov.in/",
        "hi": {
            "summary": "गोदाम, कोल्ड स्टोरेज और प्रसंस्करण इकाइयों जैसे कटाई-पश्चात बुनियादी ढांचे के लिए मध्यम-दीर्घकालिक वित्त।",
            "benefits": "₹2 करोड़ तक के ऋण पर 3% ब्याज सहायता और क्रेडिट गारंटी।",
            "eligibility": "किसान, FPO, PACS, SHG, कृषि-उद्यमी, स्टार्टअप।",
            "how_to_apply": "AIF पोर्टल पर आवेदन करें; ऋण संस्थाओं के माध्यम से स्वीकृति।",
        },
    },
    {
        "id": "pkvy",
        "name": "PKVY (Paramparagat Krishi Vikas Yojana)",
        "category": "organic",
        "level": "central",
        "image": _img("1530836369250-ef72a3f5cda8"),
        "summary": "Support for organic farming through cluster-based approach, certification and marketing assistance.",
        "benefits": "Financial assistance per hectare over 3 years for organic inputs, certification and marketing.",
        "eligibility": "Farmers willing to take up organic farming in clusters.",
        "documents": ["Identity proof", "Land records"],
        "how_to_apply": "Through state agriculture department cluster programs.",
        "official_link": "https://pgsindia-ncof.gov.in/",
        "hi": {
            "summary": "क्लस्टर आधारित जैविक खेती, प्रमाणीकरण और विपणन सहायता के लिए समर्थन।",
            "benefits": "जैविक इनपुट, प्रमाणीकरण और विपणन के लिए 3 वर्षों में प्रति हेक्टेयर वित्तीय सहायता।",
            "eligibility": "क्लस्टर में जैविक खेती अपनाने के इच्छुक किसान।",
            "how_to_apply": "राज्य कृषि विभाग के क्लस्टर कार्यक्रमों के माध्यम से।",
        },
    },
    {
        "id": "pdmc",
        "name": "Per Drop More Crop (Micro Irrigation)",
        "category": "irrigation",
        "level": "central",
        "image": _img("1625246333195-78d9c38ad449"),
        "summary": "Subsidy for drip and sprinkler irrigation systems to improve water use efficiency.",
        "benefits": "Subsidy of 55% for small/marginal farmers and 45% for others on micro-irrigation systems (state top-ups may apply).",
        "eligibility": "All farmers; priority for small and marginal farmers.",
        "documents": ["Identity proof", "Land documents", "Bank details"],
        "how_to_apply": "Through state horticulture/agriculture department portals.",
        "official_link": "https://pmksy.gov.in/",
        "hi": {
            "summary": "पानी की बचत के लिए ड्रिप और स्प्रिंकलर सिंचाई प्रणाली पर सब्सिडी।",
            "benefits": "छोटे/सीमांत किसानों को 55% और अन्य को 45% सब्सिडी (राज्य अतिरिक्त सहायता दे सकते हैं)।",
            "eligibility": "सभी किसान; छोटे और सीमांत किसानों को प्राथमिकता।",
            "how_to_apply": "राज्य उद्यानिकी/कृषि विभाग के पोर्टल से आवेदन करें।",
        },
    },
    {
        "id": "nfsm",
        "name": "National Food Security Mission (NFSM)",
        "category": "production",
        "level": "central",
        "image": _img("1592982537447-7440770cbfc9"),
        "summary": "Support to increase production of rice, wheat, pulses, coarse cereals and commercial crops via demonstrations and subsidized inputs.",
        "benefits": "Subsidized seeds, demonstrations, farm machinery assistance in mission districts.",
        "eligibility": "Farmers in identified mission districts.",
        "documents": ["Identity proof", "Land records"],
        "how_to_apply": "Through district agriculture office programs.",
        "official_link": "https://nfsm.gov.in/",
        "hi": {
            "summary": "प्रदर्शन और रियायती इनपुट के माध्यम से चावल, गेहूं, दालें और मोटे अनाज का उत्पादन बढ़ाने में सहायता।",
            "benefits": "मिशन जिलों में रियायती बीज, प्रदर्शन और कृषि यंत्र सहायता।",
            "eligibility": "चिन्हित मिशन जिलों के किसान।",
            "how_to_apply": "जिला कृषि कार्यालय के कार्यक्रमों के माध्यम से।",
        },
    },
]

FAQS = [
    {"id": "f1", "topic": "getting_started", "q": "What is KhetSarthi?", "a": "KhetSarthi (हर खेत का सारथी) is a digital platform for Indian agriculture. It connects farmers, vendors and buyers, and provides weather intelligence, AI farming help, crop disease scanning, mandi prices, demand-supply matching, schemes and farm record keeping in one place."},
    {"id": "f2", "topic": "getting_started", "q": "How do I register?", "a": "Click 'Get Started' on the home page, enter your name, email and password. Then choose your language and whether you are a Farmer or Vendor."},
    {"id": "f3", "topic": "language", "q": "Can I change my language later?", "a": "Yes. Go to Settings > Language and pick any supported language. The interface switches immediately."},
    {"id": "f4", "topic": "voice", "q": "How does the voice assistant work?", "a": "Tap the floating microphone button, allow microphone permission, and speak. You can ask about weather, prices, or navigate the app. It works best in Chrome with Hindi and English."},
    {"id": "f5", "topic": "weather", "q": "Where does weather data come from?", "a": "From Open-Meteo, a reliable free weather service. Location is used only after you grant GPS permission. Advisories are decision support, not guarantees."},
    {"id": "f6", "topic": "crop_scan", "q": "Is the crop disease scan a confirmed diagnosis?", "a": "No. The AI scan gives probable conditions with confidence levels. It is informational guidance. For serious problems, always consult your local KVK or agriculture expert."},
    {"id": "f7", "topic": "prices", "q": "Where do mandi prices come from?", "a": "From the official data.gov.in Agmarknet dataset published by the Ministry of Agriculture. If data is unavailable, we show a clear unavailable state and never fabricate prices."},
    {"id": "f8", "topic": "demand_supply", "q": "What is the Demand & Supply Exchange?", "a": "Vendors and buyers post what produce they need. Farmers can see who needs their crop nearby, and declare expected harvests so buyers find them before harvest."},
    {"id": "f9", "topic": "marketplace", "q": "How do I sell my produce?", "a": "Go to Krishi Market > Sell Produce, add crop, quantity, price and photos. Interested buyers send enquiries which you can accept and track."},
    {"id": "f10", "topic": "vendors", "q": "How is a vendor verified?", "a": "Admins review vendor business information before granting a verified badge. Unverified vendors are clearly marked. We never fabricate ratings."},
    {"id": "f11", "topic": "schemes", "q": "Are the government schemes real?", "a": "Yes, we list well-known central schemes with links to official portals. Always confirm details and deadlines on the official website before applying."},
    {"id": "f12", "topic": "expenses", "q": "How does the expense manager help?", "a": "Record seeds, fertilizer, labor and other costs per crop. KhetSarthi computes crop-wise investment, revenue and estimated profit or loss."},
    {"id": "f13", "topic": "privacy", "q": "Is my farm location shared publicly?", "a": "No. Only approximate district/village-level location is shown on listings and demand posts. Your exact GPS coordinates are never exposed publicly."},
    {"id": "f14", "topic": "account", "q": "How do I delete my account?", "a": "Go to Settings > Account > Delete Account. This permanently removes your profile and data."},
    {"id": "f15", "topic": "support", "q": "The AI answered incorrectly. What should I do?", "a": "AI answers are decision support and can make mistakes. Cross-check important decisions with your local agriculture office or KVK, and use the Help Center to report issues."},
]

COMMODITIES = [
    {"key": "tomato", "name": "Tomato", "name_hi": "टमाटर", "category": "vegetables"},
    {"key": "potato", "name": "Potato", "name_hi": "आलू", "category": "vegetables"},
    {"key": "onion", "name": "Onion", "name_hi": "प्याज", "category": "vegetables"},
    {"key": "cauliflower", "name": "Cauliflower", "name_hi": "फूलगोभी", "category": "vegetables"},
    {"key": "cabbage", "name": "Cabbage", "name_hi": "पत्तागोभी", "category": "vegetables"},
    {"key": "brinjal", "name": "Brinjal", "name_hi": "बैंगन", "category": "vegetables"},
    {"key": "okra", "name": "Bhindi (Okra)", "name_hi": "भिंडी", "category": "vegetables"},
    {"key": "green_chilli", "name": "Green Chilli", "name_hi": "हरी मिर्च", "category": "vegetables"},
    {"key": "mango", "name": "Mango", "name_hi": "आम", "category": "fruits"},
    {"key": "banana", "name": "Banana", "name_hi": "केला", "category": "fruits"},
    {"key": "guava", "name": "Guava", "name_hi": "अमरूद", "category": "fruits"},
    {"key": "papaya", "name": "Papaya", "name_hi": "पपीता", "category": "fruits"},
    {"key": "wheat", "name": "Wheat", "name_hi": "गेहूं", "category": "grains"},
    {"key": "paddy", "name": "Paddy (Rice)", "name_hi": "धान (चावल)", "category": "grains"},
    {"key": "maize", "name": "Maize", "name_hi": "मक्का", "category": "grains"},
    {"key": "bajra", "name": "Bajra", "name_hi": "बाजरा", "category": "grains"},
    {"key": "arhar", "name": "Arhar (Tur) Dal", "name_hi": "अरहर (तूर) दाल", "category": "pulses"},
    {"key": "moong", "name": "Moong Dal", "name_hi": "मूंग दाल", "category": "pulses"},
    {"key": "chana", "name": "Chana (Gram)", "name_hi": "चना", "category": "pulses"},
    {"key": "masoor", "name": "Masoor Dal", "name_hi": "मसूर दाल", "category": "pulses"},
    {"key": "turmeric", "name": "Turmeric", "name_hi": "हल्दी", "category": "spices"},
    {"key": "ginger", "name": "Ginger", "name_hi": "अदरक", "category": "spices"},
    {"key": "garlic", "name": "Garlic", "name_hi": "लहसुन", "category": "spices"},
    {"key": "coriander", "name": "Coriander", "name_hi": "धनिया", "category": "spices"},
    {"key": "mustard", "name": "Mustard", "name_hi": "सरसों", "category": "oilseeds"},
    {"key": "groundnut", "name": "Groundnut", "name_hi": "मूंगफली", "category": "oilseeds"},
    {"key": "soybean", "name": "Soybean", "name_hi": "सोयाबीन", "category": "oilseeds"},
    {"key": "sugarcane", "name": "Sugarcane", "name_hi": "गन्ना", "category": "other"},
]
