import React from "react";
import { useParams, Link } from "react-router-dom";
import { useI18n } from "../lib/i18n";
import { ArrowLeft } from "@phosphor-icons/react";
import { Logo } from "../components/Shared";

const CONTENT = {
  privacy: {
    title: "Privacy Policy",
    body: [
      ["Data we collect", "Account details (name, email), your selected language and role, and information you voluntarily add: farm details, crops, expenses, listings, demand posts, reminders, chat messages and crop scan images. Location coordinates are used only after you grant GPS permission, for weather and locality display."],
      ["How data is used", "To provide platform features: weather, matching demand with supply, marketplace enquiries, AI answers and record keeping. We do not sell your personal data."],
      ["Location privacy", "Your exact GPS coordinates are never shown publicly. Listings and demand posts display only approximate district/village-level information."],
      ["AI processing", "Messages sent to KrishiAI and crop scan images are processed by a configured AI provider to generate responses. Do not include sensitive personal information in AI chats."],
      ["Third-party data sources", "Weather (Open-Meteo), reverse geocoding (OpenStreetMap Nominatim) and mandi prices (data.gov.in / Agmarknet) are fetched from public sources; your identity is not shared with them."],
      ["Account deletion", "You can permanently delete your account and all associated data from Settings → Delete Account."],
    ],
  },
  terms: {
    title: "Terms of Service",
    body: [
      ["Platform role", "KhetSarthi is a connectivity and information platform. It facilitates discovery, enquiries and lead generation between farmers, vendors and buyers. KhetSarthi is not a party to transactions between users and does not currently provide logistics, payment escrow or quality certification."],
      ["Marketplace rules", "Post only genuine listings and demand. No fake prices, misleading quantities, prohibited products or spam. Violations may result in content removal or account deactivation."],
      ["Verification", "Verified badges indicate an admin review of submitted business information; they are not a guarantee of transaction outcomes."],
      ["Acceptable use", "No abusive content, impersonation, scraping or attempts to access other users' private data."],
      ["No guarantees", "Weather advisories, AI answers, price data and matching suggestions are decision-support information, not guarantees of outcome, income or accuracy."],
      ["Grievances & support", "Use the Help Center for issues. Admins review reports of fraud, spam or abuse."],
    ],
  },
  "ai-disclaimer": {
    title: "AI Disclaimer",
    body: [
      ["Informational guidance only", "KrishiAI and the Crop Health Scanner provide informational guidance generated by AI models. They are not certified agronomic, veterinary, financial or legal advice."],
      ["Not a diagnosis", "Crop scan results are probable conditions with confidence levels — not confirmed diagnoses. For significant crop loss risk, pesticide decisions or safety concerns, consult your local Krishi Vigyan Kendra (KVK) or a qualified agricultural expert."],
      ["Uncertainty", "AI can make mistakes, misidentify diseases, or produce outdated information. Cross-check important decisions with official sources."],
      ["Data sources", "Weather comes from Open-Meteo; mandi prices from data.gov.in (Agmarknet). When live data is unavailable we show an unavailable state — we never fabricate prices or forecasts."],
      ["Predictions", "Any trend or estimate is clearly informational. Future prices and yields are never guaranteed."],
    ],
  },
};

export default function Legal() {
  const { page } = useParams();
  const { t } = useI18n();
  const doc = CONTENT[page] || CONTENT.privacy;
  return (
    <div className="min-h-screen bg-[#F9F6F0]">
      <header className="glass sticky top-0 z-30 border-b border-[#0F3821]/10">
        <div className="max-w-3xl mx-auto flex items-center gap-2 px-4 sm:px-6 h-14">
          <Link to="/" className="flex items-center gap-2 text-[#0F3821]" data-testid="legal-back-link">
            <ArrowLeft size={18} /><Logo size={32} text={t("app_name")} />
          </Link>
        </div>
      </header>
      <main className="max-w-3xl mx-auto px-4 sm:px-6 py-12">
        <h1 className="font-heading text-3xl font-bold tracking-tight mb-8" data-testid="legal-title">{doc.title}</h1>
        <div className="space-y-6">
          {doc.body.map(([h, p], i) => (
            <section key={i} className="bg-white rounded-xl border border-[#0F3821]/10 p-6">
              <h2 className="font-heading font-semibold mb-2">{h}</h2>
              <p className="text-sm text-[#4A5D51] leading-relaxed">{p}</p>
            </section>
          ))}
        </div>
        <p className="text-xs text-[#7C8D81] mt-8">Last updated: June 2026. This document describes current platform behaviour and does not claim certifications or legal compliance beyond what is stated.</p>
      </main>
    </div>
  );
}
